name: Generate and Deploy Metrics

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "pnpm"

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run Metrics Exporter
        run: pnpm generate-metrics
      
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "stats: update translation metrics and README [skip ci]"
          
          file_pattern: 'README.md data-metrics/metrics.json'